apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend

spec:
  rules:
    - http:
        paths:
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.apps.orderManager.name }}
                port:
                  number: {{ .Values.apps.orderManager.port }}

          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.apps.userManager.name }}
                port:
                  number: {{ .Values.apps.userManager.port }}